FROM debian:bullseye

ARG AMXX_VERSION
ARG AMXX_BASE_URL
ENV AMXX_VERSION=${AMXX_VERSION:-123}
ENV AMXX_BASE_URL=${AMXX_BASE_URL:-https://google.com}

RUN apt-get update && apt-get install -y wget tar g++ make

RUN dpkg --add-architecture i386 && \
    apt-get update && \
    apt-get install -y libc6:i386 libstdc++6:i386

WORKDIR /opt

COPY build-war3xp.sh /usr/local/bin/
RUN chmod +x /usr/local/bin/build-war3xp.sh

WORKDIR /workspace

ENTRYPOINT ["/usr/local/bin/build-war3xp.sh"]
